services:
  whoami:
    image: traefik/whoami:v1.10.3
    container_name: traefik-whoami
    restart: unless-stopped
    environment:
      TZ: ${TZ}
      PUID: ${PUID}
      PGID: ${PGID}
    labels:
      traefik.enable: true
      traefik.http.routers.whoami.entrypoints: websecure
      traefik.http.routers.whoami.rule: Host(`whoami.$BASE_DOMAIN`)
      homepage.group: Infrastructure
      homepage.name: WhoAmI
      #homepage.icon: https://www.gravatar.com/avatar/27caca9bcd7fd7f7412ca5255c9ae2d0?s=160
      homepage.href: https://whoami.$BASE_DOMAIN
      homepage.description: whoami/echo service
