---
# For configuration options and examples, please see:
# https://gethomepage.dev/latest/configs/settings

providers:
  openweathermap: openweathermapapikey
  weatherapi: weatherapiapikey

layout:
  - Servarr:
      style: columns
  - Torrent:
      style: columns
  - Infrastructure:
      style: columns
  - Others:
      style: columns
