services:
  homepage:
    image: ghcr.io/gethomepage/homepage:v0.9.10
    container_name: homepage
    restart: unless-stopped
    environment:
      TZ: ${TZ}
      PUID: ${PUID}
      PGID: ${PGID}
      LOG_TARGETS: stdout
    labels:
      traefik.enable: true
      traefik.http.routers.homepage.entrypoints: websecure
      traefik.http.routers.homepage.rule: Host(`homepage.$BASE_DOMAIN`)
      traefik.http.services.homepage.loadbalancer.server.port: 3000
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./config:/app/config
