# based on:
# https://docs.opencloud.eu/docs/admin/getting-started/container/docker-compose/docker-compose-base
services:
  opencloud:
    image: opencloudeu/opencloud:7.2.4
    restart: unless-stopped
    user: ${PUID}:${PGID}
    healthcheck:
      test: ["CMD-SHELL", "curl -fsSI http://localhost:9200 || exit 1"]
      start_period: 30s
    volumes:
      - ${STORAGE_PATH}/opencloud/config:/etc/opencloud
      - ${STORAGE_PATH}/opencloud/data:/var/lib/opencloud
      # TODO: add photo - ${STORAGE_PATH}/opencloud/shared_photos:/var/lib/opencloud/storage/shared_photos
    environment:
      TZ: ${TZ}
      PROXY_TLS: false
      OC_URL: https://opencloud.$BASE_DOMAIN
      OC_ADD_RUN_SERVICES: collaboration
      COLLABORATION_APP_NAME: OnlyOffice
      COLLABORATION_APP_PRODUCT: OnlyOffice
      COLLABORATION_APP_DESCRIPTION: Open office documents with OnlyOffice
      COLLABORATION_APP_ADDR: https://onlyoffice.$BASE_DOMAIN
      COLLABORATION_STORE: memory
      COLLABORATION_WOPI_SRC: https://onlyoffice.$BASE_DOMAIN
      COLLABORATION_WOPI_SECRET: $ONLYOFFICE_JWT_KEY
      COLLABORATION_WOPI_DISABLE_CHAT: true
    labels:
      traefik.enable: true
      traefik.http.routers.opencloud.entrypoints: websecure
      traefik.http.routers.opencloud.rule: Host(`opencloud.$BASE_DOMAIN`)
      traefik.http.services.opencloud.loadbalancer.server.port: 9200
      # homepage
      homepage.group: Others
      homepage.name: OpenCloud
      homepage.icon: open-cloud-dark.svg
      homepage.href: https://opencloud.$BASE_DOMAIN
      homepage.description: Personal cloud

networks:
  default:
    external: true
    name: proxy
