# based on:
# https://github.com/stilicho2011/ubuntu_rep/blob/main/onlyoffice/docker-compose.yaml
# https://github.com/ONLYOFFICE/Docker-DocumentServer/blob/master/docker-compose.yml
services:
  onlyoffice:
    image: onlyoffice/documentserver:9.4.0
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8000/info/info.json" ]
      start_period: 60s
    volumes:
      - ${STORAGE_PATH}/onlyoffice/data:/var/www/onlyoffice/Data
      - ${STORAGE_PATH}/onlyoffice/cache:/var/lib/onlyoffice/documentserver/App_Data/cache/files
      - ${STORAGE_PATH}/onlyoffice/public:/var/www/onlyoffice/documentserver-example/public/files
      - ${STORAGE_PATH}/onlyoffice/fonts:/usr/share/fonts
    environment:
      WOPI_ENABLED: true
      JWT_ENABLED: true
      JWT_SECRET: ${ONLYOFFICE_JWT_KEY}
      JWT_HEADER: Authorization
      JWT_IN_BODY: 'true'
    labels:
      traefik.enable: true
      traefik.http.routers.onlyoffice.entrypoints: websecure
      traefik.http.routers.onlyoffice.rule: Host(`onlyoffice.$BASE_DOMAIN`)
      # homepage
      homepage.group: Others
      homepage.name: OnlyOffice(NextCloud)
      homepage.icon: onlyoffice.svg
      homepage.description: Personal office suite

networks:
  default:
    external: true
    name: proxy
